### ISSUE TITLE
Query with spaces breaks

### ISSUE THREAD

**Issue by sc-steven** [hisxo/gitGraber#11]
Was attempting to do a multi query search like the below but it breaks due to the space in the middle. I tried adding %20 instead of the space but the encoding breaks it.

`-q "org:TestOrg is:public"`

Public org only repo's

**Comment by rmarot** [comment]
Hi,

We are looking into this and will let you know.

Thanks

**Comment by rmarot** [comment]
We did some tests on our side and see nothing special regarding the space. What do you mean by "it breaks ?" Do you have any specific error or some bad results ? 

Thanks
