### ISSUE TITLE
Gitgraber throw this error on executing the commands for specific domain

### ISSUE THREAD

**Issue by Cybernewbies** [hisxo/gitGraber#23]
Hi Team,

Even though I have installed and configured the token to work, but prompted with below issues,

#python3 gitGraber.py -k filename_keywords.txt -q \"xyz.net\"
Traceback (most recent call last):
  File "gitGraber.py", line 340, in <module>
    initFile(args.wordlist)
  File "gitGraber.py", line 30, in initFile
    if not name or os.path.getsize(name) == 0:
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'filename_keywords.txt'

How to proceed further without any issues, I need to know the reason behind it.

**Comment by H4ckW0lf** [comment]
Hey !

I have the same problem :/

**Comment by rmarot** [comment]
Hey, what's in your filename_keywords.txt file ? Did you try -k wordlists/filename_keywords.txt ?
