### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by airwawekz** [hisxo/gitGraber#25]
I edited config.py with my github token and I got this:

```
[i] Sleeping 61 sec
[i] Status code : 401
[!] Unexpected HTTP response 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
[i] Github query : https://api.github.com/search/code?q=%22snapchat.com%22%20access_key&sort=indexed&o=desc

```

I missed something?

**Comment by AlishahMughal123** [comment]
Kindly check the issue
am getting same issue

**Comment by rmarot** [comment]
How did you add it ? It should be like :
`GITHUB_TOKENS = ["TOKEN1"]` for one token or `GITHUB_TOKENS = ["TOKEN1","TOKEN2","TOKEN3"]` for several tokens.

**Comment by attacker007** [comment]
Getting same Error... 

Edited like this in tokens.py file

```

tokensList.append(Token('GITHUB_CLIENT_SECRET', 'XXXXXXXd13bb6cXXX104f320537XXXXXXXX'))


```

**Comment by rmarot** [comment]
That's not the way to configure it. Please refer to the documentation https://github.com/hisxo/gitgraber#configuration and above comment.
