### ISSUE TITLE
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}

### ISSUE THREAD

**Issue by hasher313** [hisxo/gitGraber#32]
hi man!!
i got this error whenever i run the tool without any result !! any help?

``
`[i] Github query : https://api.github.com/search/code?q=%20%20database_host&sort=indexed&o=desc
[i] Status code : 401
[i] Status code : 401
[!] Unexpected HTTP response 401
[!] Unexpected HTTP response 401
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

**Comment by rmarot** [comment]
Hi,

How does your config file look like ? Did you following config steps from the README ?

**Comment by hasher313** [comment]
done, it's work now , thank you !
