### ISSUE TITLE
No url results !

### ISSUE THREAD

**Issue by arkxdns** [hisxo/gitGraber#6]
Hello,

I put two tokens in config file.

I'v got no results from "yahoo" keyword (or anything else) like on your command line example : 

`python3 gitGraber.py -k wordlists/keywords.txt -q "yahoo" -s`
Only this output 
```
[+] Github query : https://api.github.com/search/code?q=yahoo access_key&sort=indexed&o=desc
[i] Status code : 200
```
No any kind of urls.

Any ideas ?

**Comment by hisxo** [comment]
Hello,

How long have you used the tool? How long did you wait? All keywords have been executed and no results?

Regards,
Adrien

**Comment by dtnml** [comment]
Great tool...


I have used the tool, **yet to review the code** but my simple logic is that it returns output if the query ie yahoo and a regrex of keywords ie AWS_key is found...

**Comment by hisxo** [comment]
Yes. On CLI you can see the URL request sended to GitHub and response statut code. If the conditions are met, that is :

- a sensitive key is found
- the second keyword specified via the -q option is present

You will see direclty on the CLI (and on Slack) the URL of the repo, the sensitive key found and the date of the commit.

Please @arkxdns open an issue if you find an issue which block to run gitGraber.

I close the discussion.

Regards,
Adrien
