### ISSUE TITLE
Exception HTTPSConnectionPool

### ISSUE THREAD

**Issue by securITymania** [hisxo/gitGraber#9]
Some times tool throws an error like below

```Exception HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sourcecrypto/sourcecrypto.github.io/fe56883109388622f010e0163cdef88721e25890/_site/posts/Bitcoin/lightning/index.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7efdb59fc350>: Failed to establish a new connection: [Errno -2] Name or service not known'))```

**Comment by rmarot** [comment]
Hi,

It sounds like this issue is local to your machine because it is not able to connect / resolv the raw.githubusercontent.com domain name (connection flap or DNS issue ?). 

Does this issue appear often ? 

Thanks

**Comment by securITymania** [comment]
No, But Sometimes.

**Comment by rmarot** [comment]
Hi @securITymania 

We will do a fix to catch the Exception properly, however this issue seems to be on the client side (DNS resolution issue for example), so I think that we will not be able to do any improvement. 

I will close as soon as we will have updated with the exception management.

**Comment by rmarot** [comment]
Modification added.
